;; tei-html-docs-p5.el -- Show TEI guidelines for current element
;;
;; Copyright (C) 2005 P J Heslin
;;
;; Author: Peter Heslin <p.j.heslin@dur.ac.uk>
;; URL: http://www.dur.ac.uk/p.j.heslin/Software/Emacs/Download/tei-html-docs-p5.el
;; Version: 1.0
;;
;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; If you do not have a copy of the GNU General Public License, you
;; can obtain one by writing to the Free Software Foundation, Inc., 59
;; Temple Place - Suite 330, Boston, MA 02111-1307, USA.

;;; Commentary:
;;
;; A quick but useful hack for TEI-P5 XML documents: it provides a
;; function that looks up the name of the element before point and
;; displays the TEI guidelines for that element.
;;
;; You need to download and unzip the HTML documentation from
;; http://tei.sf.net -- the filename will look something like
;; tei-p5-doc-0.1.9.zip
;;
;; Now set the variable tei-html-docs-p5-dir to the directory with all of
;; the ref-*.html files you just unzipped, like so:
;;
;;    (setq tei-html-docs-p5-dir "~/TEI_P5/")
;;
;; If you don't set tei-html-docs-p5-dir, then the on-line version of the
;; docs on the TEI web-site will be used instead.
;;
;; In order of preference, the docs will be viewed with emacs-w3m
;; (http://emacs-w3m.namazu.org/), which requires w3m (apt-get w3m or
;; see http://w3m.sourceforge.net/), or with w3, a browser written in
;; Emacs Lisp (see http://www.gnu.org/software/w3/ for the CVS
;; version, which handles nested tables, as required here); finally,
;; if neither of these are available, an external web browser will
;; be launched.
;;
;; Then put this package somewhere in your load-path, require it, and
;; assign the function tei-html-docs-p5-element-at-point to a
;; key-binding, with lines like these in your .emacs (this example
;; assumes you use nxml-mode to edit TEI documents):
;;
;;    (require 'tei-html-docs-p5)
;;    (define-key nxml-mode-map (kbd "<S-f1>") 'tei-html-docs-p5-element-at-point)

;;; Code:

(defvar tei-html-docs-p5-dir nil
  "Directory containing the TEI P5 documentation in HTML format,
  obtained from http://tei.sf.net.  Make sure it ends in a /.  If
  NIL, use the on-line version.")

(defvar tei-html-docs-p5-url "http://www.tei-c.org/P5/Guidelines/")

(defvar tei-html-docs-p5-view-command 'browse-url
  "Command to use to view the TEI documentation")
(setq tei-html-docs-p5-view-command
      (cond ((fboundp 'w3m-goto-url) 'w3m-goto-url)
            ((fboundp 'w3-fetch) 'w3-fetch)
            (t 'browse-url)))

(defun tei-html-docs-p5-element-at-point ()
  (interactive)
  (save-excursion
    (if (and (re-search-backward "<[^!?/>]" nil t)
             (re-search-forward "\\=<\\([^!?/>][^ \t\r\n>]*\\)" nil t))
        (let ((file (cadr (assoc (match-string 1)
                                 tei-html-docs-p5-element-alist))))
          (if file
              (funcall tei-html-docs-p5-view-command
                       (if tei-html-docs-p5-dir
                           (concat "file://"
                                   (expand-file-name
                                    (concat tei-html-docs-p5-dir file)))
                         (concat tei-html-docs-p5-url file)))
            (message "%s" (concat "Error: element "
                                  (match-string 1) " not found in docs"))))
      (message "%s" "Error: no element found."))))
  

;; Almost all, but unfortunately not quite all of the files are of the
;; form ref-element.html.  For some reason, some element names have
;; been munged slightly.  So instead of doing (concat "ref-" (upcase
;; (match-string 1)) ".html") we have to supply this messy list.  It
;; was generated with this command line:
;;
;; grep h1 ref-* | perl -ne 'print "(\"", m/&lt;(.*?)&gt;/, "\" \"", m/(ref-.*?html)/, "\")\n"'  | grep -v '^(""'

(defvar tei-html-docs-p5-element-alist 
  `(("abbr" "ref-abbr.html")
("ab" "ref-ab.html")
("accMat" "ref-accMat.html")
("acquisition" "ref-acquisition.html")
("activity" "ref-activity.html")
("actor" "ref-actor.html")
("add" "ref-add.html")
("additional" "ref-additional.html")
("additions" "ref-additions.html")
("addName" "ref-addName.html")
("address" "ref-address.html")
("addrLine" "ref-addrLine.html")
("addSpan" "ref-addSpan.html")
("adminInfo" "ref-adminInfo.html")
("affiliation" "ref-affiliation.html")
("altGrp" "ref-altGrp.html")
("alt" "ref-alt.html")
("altIdent" "ref-altIdent.html")
("altIdentifier" "ref-altIdentifier.html")
("altName" "ref-altName.html")
("analytic" "ref-analytic.html")
("anchor" "ref-anchor.html")
("app" "ref-app.html")
("arc" "ref-arc.html")
("argument" "ref-argument.html")
("attDef" "ref-attDef.html")
("att" "ref-att.html")
("attList" "ref-attList.html")
("attRef" "ref-attRef.html")
("author" "ref-author.html")
("authority" "ref-authority.html")
("availability" "ref-availability.html")
("back" "ref-back.html")
("biblFull" "ref-biblFull.html")
("bibl" "ref-bibl.html")
("biblItem" "ref-biblItem.html")
("biblScope" "ref-biblScope.html")
("biblStruct" "ref-biblStruct.html")
("bicond" "ref-bicond.html")
("binary" "ref-binary.html")
("binaryObject" "ref-binaryObject.html")
("bindingDesc" "ref-bindingDesc.html")
("binding" "ref-binding.html")
("birth" "ref-birth.html")
("bloc" "ref-bloc.html")
("body" "ref-body.html")
("broadcast" "ref-broadcast.html")
("byline" "ref-byline.html")
("caesura" "ref-caesura.html")
("camera" "ref-camera.html")
("caption" "ref-caption.html")
("case" "ref-case.html")
("castGroup" "ref-castGroup.html")
("castItem" "ref-castItem.html")
("castList" "ref-castList.html")
("catchwords" "ref-catchwords.html")
("catDesc" "ref-catDesc.html")
("category" "ref-category.html")
("catRef" "ref-catRef.html")
("cb" "ref-cb.html")
("cell" "ref-cell.html")
("certainty" "ref-certainty.html")
("change" "ref-change.html")
("channel" "ref-channel.html")
("charDesc" "ref-charDesc.html")
("char" "ref-char.html")
("charName" "ref-charName.html")
("charProp" "ref-charProp.html")
("choice" "ref-choice.html")
("c" "ref-c.html")
("cit" "ref-cit.html")
("classCode" "ref-classCode.html")
("classDecl" "ref-classDecl.html")
("classes" "ref-classes.html")
("classSpec" "ref-classSpec.html")
("cl" "ref-cl.html")
("closer" "ref-closer.html")
("code" "ref-code.html")
("col" "ref-col.html")
("collation" "ref-collation.html")
("collection" "ref-collection.html")
("coll" "ref-coll.html")
("colloc" "ref-colloc.html")
("colophon" "ref-colophon.html")
("cond" "ref-cond.html")
("condition" "ref-condition.html")
("constitution" "ref-constitution.html")
("content" "ref-content.html")
("correction" "ref-correction.html")
("corr" "ref-corr.html")
("country" "ref-country.html")
("creation" "ref-creation.html")
("custEvent" "ref-custEvent.html")
("custodialHist" "ref-custodialHist.html")
("damage" "ref-damage.html")
("datatype" "ref-datatype.html")
("date" "ref-date.html")
("dateline" "ref-dateline.html")
("dateRange" "ref-dateRange.html")
("dateStruct" "ref-dateStruct.html")
("day" "ref-day.html")
("decoDesc" "ref-decoDesc.html")
("decoNote" "ref-decoNote.html")
("default" "ref-default.html")
("defaultVal" "ref-defaultVal.html")
("def" "ref-def.html")
("del" "ref-del.html")
("delSpan" "ref-delSpan.html")
("depth" "ref-depth.html")
("derivation" "ref-derivation.html")
("desc" "ref-desc.html")
("dicteg" "ref-dicteg.html")
("dictScrap" "ref-dictScrap.html")
("dimensions" "ref-dimensions.html")
("distance" "ref-distance.html")
("distinct" "ref-distinct.html")
("distributor" "ref-distributor.html")
("div0" "ref-div0.html")
("div1" "ref-div1.html")
("div2" "ref-div2.html")
("div3" "ref-div3.html")
("div4" "ref-div4.html")
("div5" "ref-div5.html")
("div6" "ref-div6.html")
("div7" "ref-div7.html")
("divGen" "ref-divGen.html")
("div" "ref-div.html")
("docAuthor" "ref-docAuthor.html")
("docDate" "ref-docDate.html")
("docEdition" "ref-docEdition.html")
("docImprint" "ref-docImprint.html")
("docTitle" "ref-docTitle.html")
("domain" "ref-domain.html")
("edition" "ref-edition.html")
("editionStmt" "ref-editionStmt.html")
("editor" "ref-editor.html")
("editorialDecl" "ref-editorialDecl.html")
("education" "ref-education.html")
("eg" "ref-eg.html")
("egXML" "ref-egXML.html")
("eLeaf" "ref-eLeaf.html")
("elementSpec" "ref-elementSpec.html")
("emph" "ref-emph.html")
("encodingDesc" "ref-encodingDesc.html")
("entryFree" "ref-entryFree.html")
("entry" "ref-entry.html")
("epigraph" "ref-epigraph.html")
("epilogue" "ref-epilogue.html")
("equipment" "ref-equipment.html")
("equiv" "ref-equiv.html")
("eTree" "ref-eTree.html")
("etym" "ref-etym.html")
("event" "ref-event.html")
("exemplum" "ref-exemplum.html")
("expan" "ref-expan.html")
("explicit" "ref-explicit.html")
("extent" "ref-extent.html")
("factuality" "ref-factuality.html")
("fDecl" "ref-fDecl.html")
("fDescr" "ref-fDescr.html")
("f" "ref-f.html")
("figDesc" "ref-figDesc.html")
("figure" "ref-figure.html")
("fileDesc" "ref-fileDesc.html")
("filiation" "ref-filiation.html")
("finalRubric" "ref-finalRubric.html")
("firstLang" "ref-firstLang.html")
("fLib" "ref-fLib.html")
("foliation" "ref-foliation.html")
("foreign" "ref-foreign.html")
("foreName" "ref-foreName.html")
("forestGrp" "ref-forestGrp.html")
("forest" "ref-forest.html")
("form" "ref-form.html")
("formula" "ref-formula.html")
("fragmentPattern" "ref-fragmentPattern.html")
("front" "ref-front.html")
("fsConstraints" "ref-fsConstraints.html")
("fsdDecl" "ref-fsdDecl.html")
("fsDecl" "ref-fsDecl.html")
("fsDescr" "ref-fsDescr.html")
("fs" "ref-fs.html")
("funder" "ref-funder.html")
("fvLib" "ref-fvLib.html")
("fw" "ref-fw.html")
("gap" "ref-gap.html")
("gen" "ref-gen.html")
("genName" "ref-genName.html")
("geog" "ref-geog.html")
("geogName" "ref-geogName.html")
("g" "ref-g.html")
("gi" "ref-gi.html")
("gloss" "ref-gloss.html")
("glyph" "ref-glyph.html")
("glyphName" "ref-glyphName.html")
("gramGrp" "ref-gramGrp.html")
("gram" "ref-gram.html")
("graph" "ref-graph.html")
("graphic" "ref-graphic.html")
("group" "ref-group.html")
("handDesc" "ref-handDesc.html")
("hand" "ref-hand.html")
("handList" "ref-handList.html")
("handNote" "ref-handNote.html")
("handShift" "ref-handShift.html")
("head" "ref-head.html")
("headItem" "ref-headItem.html")
("headLabel" "ref-headLabel.html")
("height" "ref-height.html")
("heraldry" "ref-heraldry.html")
("hi" "ref-hi.html")
("history" "ref-history.html")
("hom" "ref-hom.html")
("hour" "ref-hour.html")
("hyphenation" "ref-hyphenation.html")
("hyph" "ref-hyph.html")
("ident" "ref-ident.html")
("idno" "ref-idno.html")
("iff" "ref-iff.html")
("if" "ref-if.html")
("imprimatur" "ref-imprimatur.html")
("imprint" "ref-imprint.html")
("incipit" "ref-incipit.html")
("index" "ref-index.html")
("indexTerm" "ref-indexTerm.html")
("iNode" "ref-iNode.html")
("institution" "ref-institution.html")
("interaction" "ref-interaction.html")
("interpGrp" "ref-interpGrp.html")
("interp" "ref-interp.html")
("interpretation" "ref-interpretation.html")
("item" "ref-item.html")
("itype" "ref-itype.html")
("joinGrp" "ref-joinGrp.html")
("join" "ref-join.html")
("keywords" "ref-keywords.html")
("kinesic" "ref-kinesic.html")
("label" "ref-label.html")
("lacunaEnd" "ref-lacunaEnd.html")
("lacunaStart" "ref-lacunaStart.html")
("lang" "ref-lang.html")
("langKnown" "ref-langKnown.html")
("language" "ref-language.html")
("langUsage" "ref-langUsage.html")
("layoutDesc" "ref-layoutDesc.html")
("layout" "ref-layout.html")
("lb" "ref-lb.html")
("lbl" "ref-lbl.html")
("leaf" "ref-leaf.html")
("lem" "ref-lem.html")
("lg1" "ref-lg1.html")
("lg2" "ref-lg2.html")
("lg3" "ref-lg3.html")
("lg4" "ref-lg4.html")
("lg5" "ref-lg5.html")
("lg" "ref-lg.html")
("l" "ref-l.html")
("line" "ref-line.html")
("linkGrp" "ref-linkGrp.html")
("link" "ref-link.html")
("listBibl" "ref-listBibl.html")
("list" "ref-list.html")
("listRef" "ref-listRef.html")
("locale" "ref-locale.html")
("localName" "ref-localName.html")
("locus" "ref-locus.html")
("macroSpec" "ref-macroSpec.html")
("mapping" "ref-mapping.html")
("material" "ref-material.html")
("measure" "ref-measure.html")
("meeting" "ref-meeting.html")
("memberOf" "ref-memberOf.html")
("mentioned" "ref-mentioned.html")
("metDecl" "ref-metDecl.html")
("metSym" "ref-metSym.html")
("m" "ref-m.html")
("milestone" "ref-milestone.html")
("minute" "ref-minute.html")
("moduleRef" "ref-moduleRef.html")
("moduleSpec" "ref-moduleSpec.html")
("monogr" "ref-monogr.html")
("month" "ref-month.html")
("mood" "ref-mood.html")
("move" "ref-move.html")
("msContents" "ref-msContents.html")
("msDescription" "ref-msDescription.html")
("msIdentifier" "ref-msIdentifier.html")
("msItem" "ref-msItem.html")
("msItemStruct" "ref-msItemStruct.html")
("msPart" "ref-msPart.html")
("musicNotation" "ref-musicNotation.html")
("name" "ref-name.html")
("nameLink" "ref-nameLink.html")
("node" "ref-node.html")
("normalization" "ref-normalization.html")
("note" "ref-note.html")
("notesStmt" "ref-notesStmt.html")
("number" "ref-number.html")
("numeric" "ref-numeric.html")
("num" "ref-num.html")
("objectDesc" "ref-objectDesc.html")
("occasion" "ref-occasion.html")
("occupation" "ref-occupation.html")
("offset" "ref-offset.html")
("opener" "ref-opener.html")
("oRef" "ref-oRef.html")
("orgDivn" "ref-orgDivn.html")
("orgName" "ref-orgName.html")
("orgTitle" "ref-orgTitle.html")
("orgType" "ref-orgType.html")
("origDate" "ref-origDate.html")
("orig" "ref-orig.html")
("origin" "ref-origin.html")
("origPlace" "ref-origPlace.html")
("orth" "ref-orth.html")
("oVar" "ref-oVar.html")
("page" "ref-page.html")
("particDesc" "ref-particDesc.html")
("particLinks" "ref-particLinks.html")
("pause" "ref-pause.html")
("pb" "ref-pb.html")
("performance" "ref-performance.html")
("per" "ref-per.html")
("persName" "ref-persName.html")
("personGrp" "ref-personGrp.html")
("person" "ref-person.html")
("phr" "ref-phr.html")
("p" "ref-p.html")
("physDesc" "ref-physDesc.html")
("placeName" "ref-placeName.html")
("pos" "ref-pos.html")
("postBox" "ref-postBox.html")
("postCode" "ref-postCode.html")
("pRef" "ref-pRef.html")
("preparedness" "ref-preparedness.html")
("principal" "ref-principal.html")
("profileDesc" "ref-profileDesc.html")
("projectDesc" "ref-projectDesc.html")
("prologue" "ref-prologue.html")
("pron" "ref-pron.html")
("provenance" "ref-provenance.html")
("ptr" "ref-ptr.html")
("publicationStmt" "ref-publicationStmt.html")
("publisher" "ref-publisher.html")
("pubPlace" "ref-pubPlace.html")
("purpose" "ref-purpose.html")
("pVar" "ref-pVar.html")
("q" "ref-q.html")
("quotation" "ref-quotation.html")
("quote" "ref-quote.html")
("rdgGrp" "ref-rdgGrp.html")
("rdg" "ref-rdg.html")
("recordHist" "ref-recordHist.html")
("recording" "ref-recording.html")
("recordingStmt" "ref-recordingStmt.html")
("ref" "ref-ref.html")
("refsDecl" "ref-refsDecl.html")
("reg" "ref-reg.html")
("region" "ref-region.html")
("re" "ref-re.html")
("relation" "ref-relation.html")
("remarks" "ref-remarks.html")
("rendition" "ref-rendition.html")
("repository" "ref-repository.html")
("residence" "ref-residence.html")
("resp" "ref-resp.html")
("respons" "ref-respons.html")
("respStmt" "ref-respStmt.html")
("restore" "ref-restore.html")
("revisionDesc" "ref-revisionDesc.html")
("roleDesc" "ref-roleDesc.html")
("role" "ref-role.html")
("roleName" "ref-roleName.html")
("root" "ref-root.html")
("row" "ref-row.html")
("rs" "ref-rs.html")
("rubric" "ref-rubric.html")
("salute" "ref-salute.html")
("samplingDecl" "ref-samplingDecl.html")
("schemaSpec" "ref-schemaSpec.html")
("scriptStmt" "ref-scriptStmt.html")
("sealDesc" "ref-sealDesc.html")
("seal" "ref-seal.html")
("secFol" "ref-secFol.html")
("second" "ref-second.html")
("seg" "ref-seg.html")
("segmentation" "ref-segmentation.html")
("sense" "ref-sense.html")
("series" "ref-series.html")
("seriesStmt" "ref-seriesStmt.html")
("set" "ref-set.html")
("settingDesc" "ref-settingDesc.html")
("setting" "ref-setting.html")
("settlement" "ref-settlement.html")
("shift" "ref-shift.html")
("s" "ref-s.html")
("sic" "ref-sic.html")
("signatures" "ref-signatures.html")
("signed" "ref-signed.html")
("soCalled" "ref-soCalled.html")
("socecStatus" "ref-socecStatus.html")
("sound" "ref-sound.html")
("sourceDesc" "ref-sourceDesc.html")
("source" "ref-source.html")
("space" "ref-space.html")
("spanGrp" "ref-spanGrp.html")
("span" "ref-span.html")
("speaker" "ref-speaker.html")
("specDesc" "ref-specDesc.html")
("specGrp" "ref-specGrp.html")
("specGrpRef" "ref-specGrpRef.html")
("specList" "ref-specList.html")
("sp" "ref-sp.html")
("sponsor" "ref-sponsor.html")
("stage" "ref-stage.html")
("state" "ref-state.html")
("stdVals" "ref-stdVals.html")
("street" "ref-street.html")
("stress" "ref-stress.html")
("string" "ref-string.html")
("stringVal" "ref-stringVal.html")
("subc" "ref-subc.html")
("summary" "ref-summary.html")
("superEntry" "ref-superEntry.html")
("supplied" "ref-supplied.html")
("supportDesc" "ref-supportDesc.html")
("support" "ref-support.html")
("surname" "ref-surname.html")
("surrogates" "ref-surrogates.html")
("syll" "ref-syll.html")
("symbol" "ref-symbol.html")
("table" "ref-table.html")
("tag" "ref-tag.html")
("tagsDecl" "ref-tagsDecl.html")
("tagUsage" "ref-tagUsage.html")
("taxonomy" "ref-taxonomy.html")
("tech" "ref-tech.html")
("teiCorpus" "ref-teiCorpus.html")
("teifsd" "ref-teifsd.html")
("teiHeader" "ref-teiHeader.html")
("TEI" "ref-TEI.html")
("term" "ref-term.html")
("textClass" "ref-textClass.html")
("textDesc" "ref-textDesc.html")
("text" "ref-text.html")
("textLang" "ref-textLang.html")
("then" "ref-then.html")
("time" "ref-time.html")
("timeline" "ref-timeline.html")
("timeRange" "ref-timeRange.html")
("timeStruct" "ref-timeStruct.html")
("title" "ref-title.html")
("titlePage" "ref-titlePage.html")
("titlePart" "ref-titlePart.html")
("titleStmt" "ref-titleStmt.html")
("tns" "ref-tns.html")
("trailer" "ref-trailer.html")
("trans" "ref-trans.html")
("tree" "ref-tree.html")
("tr" "ref-tr.html")
("triangle" "ref-triangle.html")
("u" "ref-u.html")
("unclear" "ref-unclear.html")
("unicodeName" "ref-unicodeName.html")
("usg" "ref-usg.html")
("valDesc" "ref-valDesc.html")
("val" "ref-val.html")
("valItem" "ref-valItem.html")
("valList" "ref-valList.html")
("vAlt" "ref-vAlt.html")
("value" "ref-value.html")
("variantEncoding" "ref-variantEncoding.html")
("vDefault" "ref-vDefault.html")
("vername" "ref-vername.html")
("view" "ref-view.html")
("vLabel" "ref-vLabel.html")
("vMerge" "ref-vMerge.html")
("vNot" "ref-vNot.html")
("vocal" "ref-vocal.html")
("vol" "ref-vol.html")
("vRange" "ref-vRange.html")
("watermark" "ref-watermark.html")
("week" "ref-week.html")
("when" "ref-when.html")
("w" "ref-w.html")
("width" "ref-width.html")
("witDetail" "ref-witDetail.html")
("witEnd" "ref-witEnd.html")
("wit" "ref-wit.html")
("witList" "ref-witList.html")
("witness" "ref-witness.html")
("witStart" "ref-witStart.html")
("writing" "ref-writing.html")
("xr" "ref-xr.html")
("year" "ref-year.html"))
  "Translate element names to doc files.")



(provide 'tei-html-docs-p5)

